-- Partie A: mise en place environnement Snowflake
-- Utilise un role existant: remplacez <YOUR_ROLE> par votre role actif.

USE ROLE ACCOUNTADMIN;

-- 1) Warehouse / Database / Schema
CREATE WAREHOUSE IF NOT EXISTS WH_LAB
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS DB_LAB;
CREATE SCHEMA IF NOT EXISTS DB_LAB.CHAT_APP;

-- 2) Privileges donnes a un role existant
GRANT USAGE ON WAREHOUSE WH_LAB TO ROLE <YOUR_ROLE>;
GRANT USAGE ON DATABASE DB_LAB TO ROLE <YOUR_ROLE>;
GRANT USAGE ON SCHEMA DB_LAB.CHAT_APP TO ROLE <YOUR_ROLE>;

GRANT CREATE STREAMLIT ON SCHEMA DB_LAB.CHAT_APP TO ROLE <YOUR_ROLE>;
GRANT CREATE STAGE ON SCHEMA DB_LAB.CHAT_APP TO ROLE <YOUR_ROLE>;

-- 3) Acces Cortex
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE <YOUR_ROLE>;

-- 4) Recommande pour eviter les erreurs "model unavailable in your region"
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Contexte de travail pour l'app
USE ROLE <YOUR_ROLE>;
USE WAREHOUSE WH_LAB;
USE DATABASE DB_LAB;
USE SCHEMA CHAT_APP;
